HID-2099 profile
UN-OCHA/hid_api pull request #152
Opened 2020-10-15 10:34 UTC by left23

I copied from existing code to get the route for Profile, and the method for the handler, which includes the user data.
When I visit the /profile path, I get the correct template and my data when I'm logged in.

I've also added a conditional to the "login" menu item, so it displays the user's Profile name and links to /profile when user is logged in. More work needed here to add the dropdown with logout, and Settings menu item.

@rupl I'm keeping this in Draft as I work on it more. Feel free to input as I go if you have comments or suggestions.

2020-10-21 13:22 UTC, left23 commented on templates/header.ejs
> +      <link rel=stylesheet href="https://demo.commondesign-unocha-org.ahconu.org/themes/contrib/common_design/css/styles.css">
@rupl FYI needs auth before it will load.

2020-10-21 13:23 UTC, left23 commented
@rupl I've ignored the styling thus far, except to hotlink the CSS from the demo site to get the dropdowns working.

2020-10-22 13:27 UTC, left23 commented on templates/header.ejs
> +      <link rel=stylesheet href="https://demo.commondesign-unocha-org.ahconu.org/themes/contrib/common_design/css/styles.css">
No longer relevant, as I merged #154 to this branch

2020-10-22 13:27 UTC, left23 commented
> @rupl I've ignored the styling thus far, except to hotlink the CSS from the demo site to get the dropdowns working.

I've merged PR #154 so this should be easier to review without the hotlinked CSS file.

2020-10-26 11:06 UTC, rupl requested changes
This is a really great start, nice job! Since we are cleared to incrementally merge this into dev, there are a couple aspects I'd like to tweak before we merge this chunk of work:

- The main content column is quite skinny and it forces the Settings tabs onto two rows. You think we can expand the column to take up maybe two more of the Bootstrap grid columns?
- I see you re-used the focus styles on the Settings tabs, but they result in the buttons shifting as I click between them. Could we try using `outline` or at least a transparent border on the non-active links to keep them more steady?
- Maybe this is just me, but I would reverse the order of the fields on Profile editing to be Given, then Family name.

2020-10-26 11:08 UTC, rupl commented
Oops just one more thing. I think we can drop "General" and have Password be the default Settings pane.

2020-10-28 10:59 UTC, rupl approved these changes
I did one final check and noticed that the primary email address was printed twice, so I swapped it out for a loop and displayed the email confirmation status similar to HID Contacts. With that, we can get this on dev and have others look at it :shipit:

2020-10-28 11:00 UTC, merged